import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';
import * as crypto from 'crypto';

export type UserApiKeyDocument = UserApiKey & Document;

@Schema({ timestamps: true })
export class UserApiKey {
  @Prop({ required: true, unique: true })
  key: string; // plain (generated by server, shown once)

  @Prop({ required: true })
  label: string;

  @Prop({ default: 'active' })
  status: string; // active | revoked
}

export const UserApiKeySchema = SchemaFactory.createForClass(UserApiKey);

export function generateUserApiKey(): string {
  return 'uak_' + crypto.randomBytes(24).toString('hex');
}
